export const FETCH_SECTIONS_PENDING = "FETCH_SECTIONS_PENDING";
export const FETCH_SECTIONS_FULLFILLED = "FETCH_SECTIONS_FULLFILLED";
export const FETCH_SECTIONS_REJECTED = "FETCH_SECTIONS_REJECTED";
export const FETCH_EACHSECTION_PENDING = "FETCH_EACHSECTION_PENDING";
export const FETCH_EACHSECTION_FULLFILLED = "FETCH_EACHSECTION_FULLFILLED";
export const FETCH_EACHSECTION_REJECTED = "FETCH_EACHSECTION_REJECTED";
