export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_PENDING = "CREATE_USER_PENDING";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_PENDING = "LOGOUT_USER_PENDING";
export const LOGOUT_USER_FULFILLED = "LOGOUT_USER_FULFILLED";
export const LOGOUT_USER_REJECTED = "LOGOUT_USER_REJECTED";

export const COOKIES_LOAD = "COOKIES_LOAD";
export const COOKIES_LOAD_FULFILLED = "COOKIES_LOAD_FULFILLED";
export const COOKIES_LOAD_REJECTED = "COOKIES_LOAD_REJECTED";
