export const FETCH_USER = "FETCH_USER__MAIN";
export const FETCH_USER_PENDING = "FETCH_USER_PENDING__MAIN";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED__MAIN";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED__MAIN";

export const CREATE_USER = "CREATE_USER__MAIN";
export const CREATE_USER_PENDING = "CREATE_USER_PENDING__MAIN";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED__MAIN";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED__MAIN";

export const LOGOUT_USER = "LOGOUT_USER__MAIN";
export const LOGOUT_USER_PENDING = "LOGOUT_USER_PENDING__MAIN";
export const LOGOUT_USER_FULFILLED = "LOGOUT_USER_FULFILLED__MAIN";
export const LOGOUT_USER_REJECTED = "LOGOUT_USER_REJECTED__MAIN";

export const COOKIES_LOAD = "COOKIES_LOAD__MAIN";
export const COOKIES_LOAD_FULFILLED = "COOKIES_LOAD_FULFILLED__MAIN";
export const COOKIES_LOAD_REJECTED = "COOKIES_LOAD_REJECTED__MAIN";
