import { MAIN_URL } from "../../Common/utils/API";

const BUSINESS = "business/business/";
const BUSINESS_PUT = "business/business-put";
const APP_BUSINESS_APPROVAL = "businessCollection/business/";
const ALBUM = "business/album/";
const PHOTO = "business/photo/";
const PAYMENT_METHOD = "business/paymentmethod/";
const SOCIAL_LINK = "";
const COMPANY_TYPE = "business/companytype/";
const SALES_USERS_LIST = "businessCollection/sales/";
const BRANCH_ADDRESS = "business/business-branchaddress/";
const BUSINESS_BRANCH_GET = "business/business-each-section/branchAddress/";
const PRIMARY_ADDRESS = "business/business-each-section/address/";
const ABOUT = "business/business-each-section/about/";
const WORKING_HOUR = "business/business-each-section/workingHour/";
const BUSINESS_DETAILS = "business/business-each-section/basics/";
const LOGO_COVER_IMAGE = "business/business-each-section/logo-cover/";

export const BUSINESS_URL = `${MAIN_URL}/${BUSINESS}`;
export const ALBUM_URL = `${MAIN_URL}/${ALBUM}`;
export const PHOTO_URL = `${MAIN_URL}/${PHOTO}`;
export const PAYMENT_METHOD_URL = `${MAIN_URL}/${PAYMENT_METHOD}`;
export const SOCIAL_LINK_URL = `${MAIN_URL}/`;
export const COMPANY_TYPE_URL = `${MAIN_URL}/${COMPANY_TYPE}`;
export const BUSINESS_PUT_URL = `${MAIN_URL}/${BUSINESS_PUT}`;
export const APP_BUSINESS_APPROVAL_URL = `${MAIN_URL}/${APP_BUSINESS_APPROVAL}`;
export const SALES_USERS_LIST_URL = `${MAIN_URL}/${SALES_USERS_LIST}`;
export const BRANCH_ADDRESS_URL = `${MAIN_URL}/${BRANCH_ADDRESS}`;
export const BUSINESS_BRANCH_GET_URL = `${MAIN_URL}/${BUSINESS_BRANCH_GET}`;
export const PRIMARY_ADDRESS_URL_GET_URL = `${MAIN_URL}/${PRIMARY_ADDRESS}`;
export const ABOUT_GET_URL = `${MAIN_URL}/${ABOUT}`;
export const WORKING_HOUR_GET_URL = `${MAIN_URL}/${WORKING_HOUR}`;
export const BUSINESS_DETAILS_GET_URL = `${MAIN_URL}/${BUSINESS_DETAILS}`;
export const LOGO_COVER_IMAGE_GET_URL = `${MAIN_URL}/${LOGO_COVER_IMAGE}`;
export { MAIN_URL };
