export const FETCH_INDUSTRY = "FETCH_INDUSTRY__INDIVIDUAL";
export const FETCH_INDUSTRY_PENDING = "FETCH_INDUSTRY_PENDING__INDIVIDUAL";
export const FETCH_INDUSTRY_FULFILLED = "FETCH_INDUSTRY_FULFILLED__INDIVIDUAL";
export const FETCH_INDUSTRY_REJECTED = "FETCH_INDUSTRY_REJECTED__INDIVIDUAL";

export const EDIT_EXPERIENCE = "EDIT_EXPERIENCE__INDIVIDUAL";
export const EDIT_EXPERIENCE_FULFILLED =
  "EDIT_EXPERIENCE_FULFILLED__INDIVIDUAL";
export const EDIT_EXPERIENCE_PENDING = "EDIT_EXPERIENCE_PENDING__INDIVIDUAL";
export const EDIT_EXPERIENCE_REJECTED = "EDIT_EXPERIENCE_REJECTED__INDIVIDUAL";

export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE__INDIVIDUAL";
export const DELETE_EXPERIENCE_FULFILLED =
  "DELETE_EXPERIENCE_FULFILLED__INDIVIDUAL";
export const DELETE_EXPERIENCE_PENDING =
  "DELETE_EXPERIENCE_PENDING__INDIVIDUAL";
export const DELETE_EXPERIENCE_REJECTED =
  "DELETE_EXPERIENCE_REJECTED__INDIVIDUAL";

export const DELETE_EDUCATION = "DELETE_EDUCATION__INDIVIDUAL";
export const DELETE_EDUCATION_FULFILLED =
  "DELETE_EDUCATION_FULFILLED__INDIVIDUAL";
export const DELETE_EDUCATION_PENDING = "DELETE_EDUCATION_PENDING__INDIVIDUAL";
export const DELETE_EDUCATION_REJECTED =
  "DELETE_EDUCATION_REJECTED__INDIVIDUAL";

export const ADD_EDUCATION = "ADD_EDUCATION__INDIVIDUAL";
export const ADD_EDUCATION_FULFILLED = "ADD_EDUCATION_FULFILLED__INDIVIDUAL";
export const ADD_EDUCATION_PENDING = "ADD_EDUCATION_PENDING__INDIVIDUAL";
export const ADD_EDUCATION_REJECTED = "ADD_EDUCATION_REJECTED__INDIVIDUAL";

export const FETCH_EDUCATION = "FETCH_EDUCATION__INDIVIDUAL";
export const FETCH_EDUCATION_FULFILLED =
  "FETCH_EDUCATION_FULFILLED__INDIVIDUAL";
export const FETCH_EDUCATION_PENDING = "FETCH_EDUCATION_PENDING__INDIVIDUAL";
export const FETCH_EDUCATION_REJECTED = "FETCH_EDUCATION_REJECTED__INDIVIDUAL";

export const EDIT_EDUCATION_EACH = "EDIT_EDUCATION_EACH__INDIVIDUAL";
export const EDIT_EDUCATION_EACH_FULFILLED =
  "EDIT_EDUCATION_EACH_FULFILLED__INDIVIDUAL";
export const EDIT_EDUCATION_EACH_PENDING =
  "EDIT_EDUCATION_EACH_PENDING__INDIVIDUAL";
export const EDIT_EDUCATION_EACH_REJECTED =
  "EDIT_EDUCATION_EACH_REJECTED__INDIVIDUAL";

export const FETCH_EDUCATION_EACH = "FETCH_EDUCATION_EACH__INDIVIDUAL";
export const FETCH_EDUCATION_EACH_FULFILLED =
  "FETCH_EDUCATION_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_EDUCATION_EACH_PENDING =
  "FETCH_EDUCATION_EACH_PENDING__INDIVIDUAL";
export const FETCH_EDUCATION_EACH_REJECTED =
  "FETCH_EDUCATION_EACH_REJECTED__INDIVIDUAL";

export const FETCH_SKILLS = "FETCH_SKILLS__INDIVIDUAL";
export const FETCH_SKILLS_FULFILLED = "FETCH_SKILLS_FULFILLED__INDIVIDUAL";
export const FETCH_SKILLS_PENDING = "FETCH_SKILLS_PENDING__INDIVIDUAL";
export const FETCH_SKILLS_REJECTED = "FETCH_SKILLS_REJECTED__INDIVIDUAL";

export const FETCH_EXPERIENCE = "FETCH_EXPERIENCE__INDIVIDUAL";
export const FETCH_EXPERIENCE_FULFILLED =
  "FETCH_EXPERIENCE_FULFILLED__INDIVIDUAL";
export const FETCH_EXPERIENCE_PENDING = "FETCH_EXPERIENCE_PENDING__INDIVIDUAL";
export const FETCH_EXPERIENCE_REJECTED =
  "FETCH_EXPERIENCE_REJECTED__INDIVIDUAL";

export const FETCH_EXPERIENCE_EACH = "FETCH_EXPERIENCE_EACH__INDIVIDUAL";
export const FETCH_EXPERIENCE_EACH_FULFILLED =
  "FETCH_EXPERIENCE_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_EXPERIENCE_EACH_PENDING =
  "FETCH_EXPERIENCE_EACH_PENDING__INDIVIDUAL";
export const FETCH_EXPERIENCE_EACH_REJECTED =
  "FETCH_EXPERIENCE_EACH_REJECTED__INDIVIDUAL";

export const ADD_SKILLS = "ADD_SKILLS__INDIVIDUAL";
export const ADD_SKILLS_FULFILLED = "ADD_SKILLS_FULFILLED__INDIVIDUAL";
export const ADD_SKILLS_PENDING = "ADD_SKILLS_PENDING__INDIVIDUAL";
export const ADD_SKILLS_REJECTED = "ADD_SKILLS_REJECTED__INDIVIDUAL";

export const ADD_EXPERIENCE = "ADD_EXPERIENCE__INDIVIDUAL";
export const ADD_EXPERIENCE_FULFILLED = "ADD_EXPERIENCE_FULFILLED__INDIVIDUAL";
export const ADD_EXPERIENCE_PENDING = "ADD_EXPERIENCE_PENDING__INDIVIDUAL";
export const ADD_EXPERIENCE_REJECTED = "ADD_EXPERIENCE_REJECTED__INDIVIDUAL";

export const FETCH_PERSONAL_DETAILS = "FETCH_PERSONAL_DETAILS__INDIVIDUAL";
export const FETCH_PERSONAL_DETAILS_PENDING =
  "FETCH_PERSONAL_DETAILS_PENDING__INDIVIDUAL";
export const FETCH_PERSONAL_DETAILS_FULFILLED =
  "FETCH_PERSONAL_DETAILS_FULFILLED__INDIVIDUAL";
export const FETCH_PERSONAL_DETAILS_REJECTED =
  "FETCH_PERSONAL_DETAILS_REJECTED__INDIVIDUAL";

export const EDIT_PERSONAL_DETAILS = "EDIT_PERSONAL_DETAILS__INDIVIDUAL";
export const EDIT_PERSONAL_DETAILS_PENDING =
  "EDIT_PERSONAL_DETAILS_PENDING__INDIVIDUAL";
export const EDIT_PERSONAL_DETAILS_FULFILLED =
  "EDIT_PERSONAL_DETAILS_FULFILLED__INDIVIDUAL";
export const EDIT_PERSONAL_DETAILS_REJECTED =
  "EDIT_PERSONAL_DETAILS_REJECTED__INDIVIDUAL";

export const FETCH_ADDRESS_TREE_FULFILLED =
  "FETCH_ADDRESS_TREE_FULFILLED__INDIVIDUAL";
export const FETCH_ADDRESS_TREE_REJECTED =
  " FETCH_ADDRESS_TREE_REJECTED__INDIVIDUAL";
export const FETCH_ADDRESS_TREE_PENDING =
  " FETCH_ADDRESS_TREE_PENDING__INDIVIDUAL";

export const FETCH_ADDRESS_TREE_LIST_PENDING =
  " FETCH_ADDRESS_TREE_LIST_PENDING__INDIVIDUAL";

// Address
export const FETCH_COUNTRY_FULFILLED = "FETCH_COUNTRY_FULFILLED__INDIVIDUAL";
export const FETCH_COUNTRY_REJECTED = " FETCH_COUNTRY_REJECTED__INDIVIDUAL";
export const FETCH_COUNTRY_PENDING = "FETCH_COUNTRY_PENDING__INDIVIDUAL";

export const FETCH_BUSINESS_FULFILLED = "FETCH_BUSINESS_FULFILLED__INDIVIDUAL";
export const FETCH_BUSINESS_REJECTED = " FETCH_BUSINESS_REJECTED__INDIVIDUAL";
export const FETCH_BUSINESS_PENDING = "FETCH_BUSINESS_PENDING__INDIVIDUAL";
export const BUSINESS_FILTER_ON_CHANGE =
  "BUSINESS_FILTER_ON_CHANGE__INDIVIDUAL";

export const FETCH_COUNTRY_EACH_FULFILLED =
  "FETCH_COUNTRY_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_COUNTRY_EACH_REJECTED =
  " FETCH_COUNTRY_EACH_REJECTED__INDIVIDUAL";
export const FETCH_COUNTRY_EACH_PENDING =
  "FETCH_COUNTRY_EACH_PENDING__INDIVIDUAL";

export const FETCH_STATE_EACH_FULFILLED =
  "FETCH_STATE_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_STATE_EACH_REJECTED =
  " FETCH_STATE_EACH_REJECTED__INDIVIDUAL";
export const FETCH_STATE_EACH_PENDING = "FETCH_STATE_EACH_PENDING__INDIVIDUAL";

export const FETCH_DISTRICT_EACH_FULFILLED =
  "FETCH_DISTRICT_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_DISTRICT_EACH_REJECTED =
  " FETCH_DISTRICT_EACH_REJECTED__INDIVIDUAL";
export const FETCH_DISTRICT_EACH_PENDING =
  "FETCH_DISTRICT_EACH_PENDING__INDIVIDUAL";

export const FETCH_CITY_EACH_FULFILLED =
  "FETCH_CITY_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_CITY_EACH_REJECTED = " FETCH_CITY_EACH_REJECTED__INDIVIDUAL";
export const FETCH_CITY_EACH_PENDING = "FETCH_CITY_EACH_PENDING__INDIVIDUAL";

export const TOGGLE_EDIT = "TOGGLE_EDIT__INDIVIDUAL";
