export const FETCH_PERSONAL_DETAILS = "FETCH_PERSONAL_DETAILS__INDIVIDUAL";
export const FETCH_PERSONAL_DETAILS_PENDING =
  "FETCH_PERSONAL_DETAILS_PENDING__INDIVIDUAL";
export const FETCH_PERSONAL_DETAILS_FULFILLED =
  "FETCH_PERSONAL_DETAILS_FULFILLED__INDIVIDUAL";
export const FETCH_PERSONAL_DETAILS_REJECTED =
  "FETCH_PERSONAL_DETAILS_REJECTED__INDIVIDUAL";

export const EDIT_PERSONAL_DETAILS = "EDIT_PERSONAL_DETAILS__INDIVIDUAL";
export const EDIT_PERSONAL_DETAILS_PENDING =
  "EDIT_PERSONAL_DETAILS_PENDING__INDIVIDUAL";
export const EDIT_PERSONAL_DETAILS_FULFILLED =
  "EDIT_PERSONAL_DETAILS_FULFILLED__INDIVIDUAL";
export const EDIT_PERSONAL_DETAILS_REJECTED =
  "EDIT_PERSONAL_DETAILS_REJECTED__INDIVIDUAL";

export const FETCH_ADDRESS_TREE_FULFILLED =
  "FETCH_ADDRESS_TREE_FULFILLED__INDIVIDUAL";
export const FETCH_ADDRESS_TREE_REJECTED =
  " FETCH_ADDRESS_TREE_REJECTED__INDIVIDUAL";
export const FETCH_ADDRESS_TREE_PENDING =
  " FETCH_ADDRESS_TREE_PENDING__INDIVIDUAL";

export const FETCH_ADDRESS_TREE_LIST_PENDING =
  " FETCH_ADDRESS_TREE_LIST_PENDING__INDIVIDUAL";

// Address
export const FETCH_COUNTRY_FULFILLED = "FETCH_COUNTRY_FULFILLED__INDIVIDUAL";
export const FETCH_COUNTRY_REJECTED = " FETCH_COUNTRY_REJECTED__INDIVIDUAL";
export const FETCH_COUNTRY_PENDING = "FETCH_COUNTRY_PENDING__INDIVIDUAL";

export const FETCH_COUNTRY_EACH_FULFILLED =
  "FETCH_COUNTRY_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_COUNTRY_EACH_REJECTED =
  " FETCH_COUNTRY_EACH_REJECTED__INDIVIDUAL";
export const FETCH_COUNTRY_EACH_PENDING =
  "FETCH_COUNTRY_EACH_PENDING__INDIVIDUAL";

export const FETCH_STATE_EACH_FULFILLED =
  "FETCH_STATE_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_STATE_EACH_REJECTED =
  " FETCH_STATE_EACH_REJECTED__INDIVIDUAL";
export const FETCH_STATE_EACH_PENDING = "FETCH_STATE_EACH_PENDING__INDIVIDUAL";

export const FETCH_DISTRICT_EACH_FULFILLED =
  "FETCH_DISTRICT_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_DISTRICT_EACH_REJECTED =
  " FETCH_DISTRICT_EACH_REJECTED__INDIVIDUAL";
export const FETCH_DISTRICT_EACH_PENDING =
  "FETCH_DISTRICT_EACH_PENDING__INDIVIDUAL";

export const FETCH_CITY_EACH_FULFILLED =
  "FETCH_CITY_EACH_FULFILLED__INDIVIDUAL";
export const FETCH_CITY_EACH_REJECTED = " FETCH_CITY_EACH_REJECTED__INDIVIDUAL";
export const FETCH_CITY_EACH_PENDING = "FETCH_CITY_EACH_PENDING__INDIVIDUAL";

export const TOGGLE_EDIT = "TOGGLE_EDIT__INDIVIDUAL";
