export const FETCH_SECTIONS_PENDING = "FETCH_SECTIONS_PENDING";
export const FETCH_SECTIONS_FULLFILLED = "FETCH_SECTIONS_FULLFILLED";
export const FETCH_SECTIONS_REJECTED = "FETCH_SECTIONS_REJECTED";
