// home actions
export const FETCH_ECOMMERCE_CATEGORIES_PENDING =
  "FETCH_ECOMMERCE_CATEGORIES_PENDING__ECOMMERCE";
export const FETCH_ECOMMERCE_CATEGORIES_FULFILLED =
  "FETCH_ECOMMERCE_CATEGORIES_FULFILLED__ECOMMERCE";
export const FETCH_ECOMMERCE_CATEGORIES_REJECTED =
  "FETCH_ECOMMERCE_CATEGORIES_REJECTED__ECOMMERCE";
