// attributes
export const FETCH_ECOMMERCE_ATTRIBUTES_PENDING =
  "FETCH_ECOMMERCE_ATTRIBUTES_PENDING";
export const FETCH_ECOMMERCE_ATTRIBUTES_FULFILLED =
  "FETCH_ECOMMERCE_ATTRIBUTES_FULFILLED";
export const FETCH_ECOMMERCE_ATTRIBUTES_REJECTED =
  "FETCH_ECOMMERCE_ATTRIBUTES_REJECTED";

export const CREATE_PROPERTY_CATEGORY_PENDING =
  "CREATE_PROPERTY_CATEGORY_PENDING";
export const CREATE_PROPERTY_CATEGORY_FULFILLED =
  "CREATE_PROPERTY_CATEGORY_FULFILLED";
export const CREATE_PROPERTY_CATEGORY_REJECTED =
  "CREATE_PROPERTY_CATEGORY_REJECTED";

export const DELETE_PROPERTY_CATEGORY_PENDING =
  "DELETE_PROPERTY_CATEGORY_PENDING";
export const DELETE_PROPERTY_CATEGORY_FULFILLED =
  "DELETE_PROPERTY_CATEGORY_FULFILLED";
export const DELETE_PROPERTY_CATEGORY_REJECTED =
  "DELETE_PROPERTY_CATEGORY_REJECTED";

// categories
export const FETCH_ECOMMERCE_CATEGORIES_PENDING =
  "FETCH_ECOMMERCE_CATEGORIES_PENDING";
export const FETCH_ECOMMERCE_CATEGORIES_FULFILLED =
  "FETCH_ECOMMERCE_CATEGORIES_FULFILLED";
export const FETCH_ECOMMERCE_CATEGORIES_REJECTED =
  "FETCH_ECOMMERCE_CATEGORIES_REJECTED";

export const FETCH_ECOMMERCE_CATEGORY_PENDING =
  "FETCH_ECOMMERCE_CATEGORY_PENDING";
export const FETCH_ECOMMERCE_CATEGORY_FULFILLED =
  "FETCH_ECOMMERCE_CATEGORY_FULFILLED";
export const FETCH_ECOMMERCE_CATEGORY_REJECTED =
  "FETCH_ECOMMERCE_CATEGORY_REJECTED";

export const UPDATE_ECOMMERCE_CATEGORY_PENDING =
  "UPDATE_ECOMMERCE_CATEGORY_PENDING";
export const UPDATE_ECOMMERCE_CATEGORY_FULFILLED =
  "UPDATE_ECOMMERCE_CATEGORY_FULFILLED";
export const UPDATE_ECOMMERCE_CATEGORY_REJECTED =
  "UPDATE_ECOMMERCE_CATEGORY_REJECTED";

export const DELETE_ECOMMERCE_CATEGORY_PENDING =
  "DELETE_ECOMMERCE_CATEGORY_PENDING";
export const DELETE_ECOMMERCE_CATEGORY_FULFILLED =
  "DELETE_ECOMMERCE_CATEGORY_FULFILLED";
export const DELETE_ECOMMERCE_CATEGORY_REJECTED =
  "DELETE_ECOMMERCE_CATEGORY_REJECTED";

export const CREATE_ECOMMERCE_CATEGORIES_PENDING =
  "CREATE_ECOMMERCE_CATEGORIES_PENDING";
export const CREATE_ECOMMERCE_CATEGORIES_FULFILLED =
  "CREATE_ECOMMERCE_CATEGORIES_FULFILLED";
export const CREATE_ECOMMERCE_CATEGORIES_REJECTED =
  "CREATE_ECOMMERCE_CATEGORIES_REJECTED";

export const CHANGE_ACTIVE_ECOMMERCE_CATEGORY =
  "CHANGE_ACTIVE_ECOMMERCE_CATEGORY";

export const OPEN_ALL_ON_SEARCH = "OPEN_ALL_ON_SEARCH";
