export const FETCH_BUSINESS = "FETCH_BUSINESS__BUSINESS";
export const FETCH_BUSINESS_PENDING = "FETCH_BUSINESS_PENDING__BUSINESS";
export const FETCH_BUSINESS_FULFILLED = "FETCH_BUSINESS_FULFILLED__BUSINESS";
export const FETCH_BUSINESS_REJECTED = "FETCH_BUSINESS_REJECTED__BUSINESS";
