export const FETCH_BUSINESS = "FETCH_BUSINESS__BUSINESS";
export const FETCH_BUSINESS_PENDING = "FETCH_BUSINESS_PENDING__BUSINESS";
export const FETCH_BUSINESS_FULFILLED = "FETCH_BUSINESS_FULFILLED__BUSINESS";
export const FETCH_BUSINESS_REJECTED = "FETCH_BUSINESS_REJECTED__BUSINESS";

export const FETCH_INDUSTRY = "FETCH_INDUSTRY__BUSINESS";
export const FETCH_INDUSTRY_PENDING = "FETCH_INDUSTRY_PENDING__BUSINESS";
export const FETCH_INDUSTRY_FULFILLED = "FETCH_INDUSTRY_FULFILLED__BUSINESS";
export const FETCH_INDUSTRY_REJECTED = "FETCH_INDUSTRY_REJECTED__BUSINESS";

export const FETCH_INDUSTRY_EACH = "FETCH_INDUSTRY_EACH__BUSINESS";
export const FETCH_INDUSTRY_EACH_PENDING =
  "FETCH_INDUSTRY_EACH_PENDING__BUSINESS";
export const FETCH_INDUSTRY_EACH_FULFILLED =
  "FETCH_INDUSTRY_EACH_FULFILLED__BUSINESS";
export const FETCH_INDUSTRY_EACH_REJECTED =
  "FETCH_INDUSTRY_EACH_REJECTED__BUSINESS";

export const FETCH_CATEGORY_EACH = "FETCH_CATEGORY_EACH__BUSINESS";
export const FETCH_CATEGORY_EACH_PENDING =
  "FETCH_CATEGORY_EACH_PENDING__BUSINESS";
export const FETCH_CATEGORY_EACH_FULFILLED =
  "FETCH_CATEGORY_EACH_FULFILLED__BUSINESS";
export const FETCH_CATEGORY_EACH_REJECTED =
  "FETCH_CATEGORY_EACH_REJECTED__BUSINESS";

export const FETCH_CATEGORY = "FETCH_CATEGORY__BUSINESS";
export const FETCH_CATEGORY_PENDING = "FETCH_CATEGORY_PENDING__BUSINESS";
export const FETCH_CATEGORY_FULFILLED = "FETCH_CATEGORY_FULFILLED__BUSINESS";
export const FETCH_CATEGORY_REJECTED = "FETCH_CATEGORY_REJECTED__BUSINESS";

export const FETCH_SUBCATEGORY_EACH = "FETCH_SUBCATEGORY_EACH__BUSINESS";
export const FETCH_SUBCATEGORY_EACH_PENDING =
  "FETCH_SUBCATEGORY_EACH_PENDING__BUSINESS";
export const FETCH_SUBCATEGORY_EACH_FULFILLED =
  "FETCH_SUBCATEGORY_EACH_FULFILLED__BUSINESS";
export const FETCH_SUBCATEGORY_EACH_REJECTED =
  "FETCH_SUBCATEGORY_EACH_REJECTED__BUSINESS";

// AREA
export const FETCH_AREA_FULFILLED = "FETCH_AREA_FULFILLED__BUSINESS";
export const FETCH_AREA_REJECTED = " FETCH_AREA_REJECTED__BUSINESS";
export const FETCH_AREA_PENDING = "FETCH_AREA_PENDING__BUSINESS";

// COUNTRY
export const FETCH_COUNTRY_FULFILLED = "FETCH_COUNTRY_FULFILLED__BUSINESS";
export const FETCH_COUNTRY_REJECTED = " FETCH_COUNTRY_REJECTED__BUSINESS";
export const FETCH_COUNTRY_PENDING = "FETCH_COUNTRY_PENDING__BUSINESS";

export const FETCH_COUNTRY_EACH_FULFILLED =
  "FETCH_COUNTRY_EACH_FULFILLED__BUSINESS";
export const FETCH_COUNTRY_EACH_REJECTED =
  " FETCH_COUNTRY_EACH_REJECTED__BUSINESS";
export const FETCH_COUNTRY_EACH_PENDING =
  "FETCH_COUNTRY_EACH_PENDING__BUSINESS";

export const FETCH_STATE_EACH_FULFILLED =
  "FETCH_STATE_EACH_FULFILLED__BUSINESS";
export const FETCH_STATE_EACH_REJECTED = " FETCH_STATE_EACH_REJECTED__BUSINESS";
export const FETCH_STATE_EACH_PENDING = "FETCH_STATE_EACH_PENDING__BUSINESS";

export const FETCH_DISTRICT_EACH_FULFILLED =
  "FETCH_DISTRICT_EACH_FULFILLED__BUSINESS";
export const FETCH_DISTRICT_EACH_REJECTED =
  " FETCH_DISTRICT_EACH_REJECTED__BUSINESS";
export const FETCH_DISTRICT_EACH_PENDING =
  "FETCH_DISTRICT_EACH_PENDING__BUSINESS";

export const FETCH_CITY_EACH_FULFILLED = "FETCH_CITY_EACH_FULFILLED__BUSINESS";
export const FETCH_CITY_EACH_REJECTED = " FETCH_CITY_EACH_REJECTED__BUSINESS";
export const FETCH_CITY_EACH_PENDING = "FETCH_CITY_EACH_PENDING__BUSINESS";

// STATE
export const FETCH_STATE_FULFILLED = "FETCH_STATE_FULFILLED__BUSINESS";
export const FETCH_STATE_REJECTED = " FETCH_STATE_REJECTED__BUSINESS";
export const FETCH_STATE_PENDING = " FETCH_STATE_PENDING__BUSINESS";

// DISTRICT
export const FETCH_DISTRICT_FULFILLED = "FETCH_DISTRICT_FULFILLED __BUSINESS";
export const FETCH_DISTRICT_REJECTED = " FETCH_DISTRICT_REJECTED __BUSINESS";
export const FETCH_DISTRICT_PENDING = " FETCH_DISTRICT_PENDING __BUSINESS";

// CITY
export const FETCH_CITY_FULFILLED = "FETCH_CITY_FULFILLED__BUSINESS";
export const FETCH_CITY_REJECTED = " FETCH_CITY_REJECTED__BUSINESS";
export const FETCH_CITY_PENDING = " FETCH_CITY_PENDING__BUSINESS";

export const FETCH_COMPANY_TYPE_FULFILLED =
  "FETCH_COMPANY_TYPE_FULFILLED__BUSINESS";
export const FETCH_COMPANY_TYPE_REJECTED =
  " FETCH_COMPANY_TYPE_REJECTED__BUSINESS";
export const FETCH_COMPANY_TYPE_PENDING =
  " FETCH_COMPANY_TYPE_PENDING__BUSINESS";

export const FETCH_PAYMENT_METHODS_FULFILLED =
  "FETCH_PAYMENT_METHODS_FULFILLED__BUSINESS";
export const FETCH_PAYMENT_METHODS_REJECTED =
  " FETCH_PAYMENT_METHODS_REJECTED__BUSINESS";
export const FETCH_PAYMENT_METHODS_PENDING =
  " FETCH_PAYMENT_METHODS_PENDING__BUSINESS";

export const UNMOUNT_SUB_CATEGORY = "UNMOUNT_SUB_CATEGORY";
export const UNMOUNT_DISTRICT = "UNMOUNT_DISTRICT";
export const UNMOUNT_CITY = "UNMOUNT_CITY";
export const UNMOUNT_AREA = "UNMOUNT_AREA";
