export const FETCH_BUSINESS = "FETCH_BUSINESS__BUSINESS";
export const FETCH_BUSINESS_PENDING = "FETCH_BUSINESS_PENDING__BUSINESS";
export const FETCH_BUSINESS_FULFILLED = "FETCH_BUSINESS_FULFILLED__BUSINESS";
export const FETCH_BUSINESS_REJECTED = "FETCH_BUSINESS_REJECTED__BUSINESS";

export const FETCH_INDUSTRY = "FETCH_INDUSTRY__BUSINESS";
export const FETCH_INDUSTRY_PENDING = "FETCH_INDUSTRY_PENDING__BUSINESS";
export const FETCH_INDUSTRY_FULFILLED = "FETCH_INDUSTRY_FULFILLED__BUSINESS";
export const FETCH_INDUSTRY_REJECTED = "FETCH_INDUSTRY_REJECTED__BUSINESS";

export const FETCH_INDUSTRY_EACH = "FETCH_INDUSTRY_EACH__BUSINESS";
export const FETCH_INDUSTRY_EACH_PENDING =
  "FETCH_INDUSTRY_EACH_PENDING__BUSINESS";
export const FETCH_INDUSTRY_EACH_FULFILLED =
  "FETCH_INDUSTRY_EACH_FULFILLED__BUSINESS";
export const FETCH_INDUSTRY_EACH_REJECTED =
  "FETCH_INDUSTRY_EACH_REJECTED__BUSINESS";

export const FETCH_CATEGORY_EACH = "FETCH_CATEGORY_EACH__BUSINESS";
export const FETCH_CATEGORY_EACH_PENDING =
  "FETCH_CATEGORY_EACH_PENDING__BUSINESS";
export const FETCH_CATEGORY_EACH_FULFILLED =
  "FETCH_CATEGORY_EACH_FULFILLED__BUSINESS";
export const FETCH_CATEGORY_EACH_REJECTED =
  "FETCH_CATEGORY_EACH_REJECTED__BUSINESS";

export const FETCH_CATEGORY = "FETCH_CATEGORY__BUSINESS";
export const FETCH_CATEGORY_PENDING = "FETCH_CATEGORY_PENDING__BUSINESS";
export const FETCH_CATEGORY_FULFILLED = "FETCH_CATEGORY_FULFILLED__BUSINESS";
export const FETCH_CATEGORY_REJECTED = "FETCH_CATEGORY_REJECTED__BUSINESS";

export const FETCH_SUBCATEGORY_EACH = "FETCH_SUBCATEGORY_EACH__BUSINESS";
export const FETCH_SUBCATEGORY_EACH_PENDING =
  "FETCH_SUBCATEGORY_EACH_PENDING__BUSINESS";
export const FETCH_SUBCATEGORY_EACH_FULFILLED =
  "FETCH_SUBCATEGORY_EACH_FULFILLED__BUSINESS";
export const FETCH_SUBCATEGORY_EACH_REJECTED =
  "FETCH_SUBCATEGORY_EACH_REJECTED__BUSINESS";

export const UNMOUNT_SUB_CATEGORY = "UNMOUNT_SUB_CATEGORY";
