export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY__ADMIN";
export const CREATE_SUB_CATEGORY_PENDING = "CREATE_SUB_CATEGORY_PENDING__ADMIN";
export const CREATE_SUB_CATEGORY_FULFILLED =
  "CREATE_SUB_CATEGORY_FULFILLED__ADMIN";
export const CREATE_SUB_CATEGORY_REJECTED =
  "CREATE_SUB_CATEGORY_REJECTED__ADMIN";

export const FETCH_SUB_CATEGORY = "FETCH_SUB_CATEGORY__ADMIN";
export const FETCH_SUB_CATEGORY_PENDING = "FETCH_SUB_CATEGORY_PENDING__ADMIN";
export const FETCH_SUB_CATEGORY_FULFILLED =
  "FETCH_SUB_CATEGORY_FULFILLED__ADMIN";
export const FETCH_SUB_CATEGORY_REJECTED = "FETCH_SUB_CATEGORY_REJECTED__ADMIN";

export const DELETE_SUB_CATEGORY_PENDING = "DELETE_SUB_CATEGORY_PENDING__ADMIN";
export const DELETE_SUB_CATEGORY_FULFILLED =
  "DELETE_SUB_CATEGORY_FULFILLED__ADMIN";
export const DELETE_SUB_CATEGORY_REJECTED =
  "DELETE_SUB_CATEGORY_REJECTED__ADMIN";

export const CREATE_CATEGORY = "CREATE_CATEGORY__ADMIN";
export const CREATE_CATEGORY_PENDING = "CREATE_CATEGORY_PENDING__ADMIN";
export const CREATE_CATEGORY_FULFILLED = "CREATE_CATEGORY_FULFILLED__ADMIN";
export const CREATE_CATEGORY_REJECTED = "CREATE_CATEGORY_REJECTED__ADMIN";

export const DELETE_CATEGORY_PENDING = "DELETE_CATEGORY_PENDING__ADMIN";
export const DELETE_CATEGORY_FULFILLED = "DELETE_CATEGORY_FULFILLED__ADMIN";
export const DELETE_CATEGORY_REJECTED = "DELETE_CATEGORY_REJECTED__ADMIN";

export const FETCH_CATEGORY = "FETCH_CATEGORY__ADMIN";
export const FETCH_CATEGORY_PENDING = "FETCH_CATEGORY_PENDING__ADMIN";
export const FETCH_CATEGORY_FULFILLED = "FETCH_CATEGORY_FULFILLED__ADMIN";
export const FETCH_CATEGORY_REJECTED = "FETCH_CATEGORY_REJECTED__ADMIN";

export const FETCH_INDUSTRY = "FETCH_INDUSTRY__ADMIN";
export const FETCH_INDUSTRY_PENDING = "FETCH_INDUSTRY_PENDING__ADMIN";
export const FETCH_INDUSTRY_FULFILLED = "FETCH_INDUSTRY_FULFILLED__ADMIN";
export const FETCH_INDUSTRY_REJECTED = "FETCH_INDUSTRY_REJECTED__ADMIN";

export const FETCH_INDUSTRY_EACH = "FETCH_INDUSTRY_EACH__ADMIN";
export const FETCH_INDUSTRY_EACH_PENDING = "FETCH_INDUSTRY_EACH_PENDING__ADMIN";
export const FETCH_INDUSTRY_EACH_FULFILLED =
  "FETCH_INDUSTRY_EACH_FULFILLED__ADMIN";
export const FETCH_INDUSTRY_EACH_REJECTED =
  "FETCH_INDUSTRY_EACH_REJECTED__ADMIN";

export const DELETE_INDUSTRY_PENDING = "DELETE_INDUSTRY_PENDING__ADMIN";
export const DELETE_INDUSTRY_FULFILLED = "DELETE_INDUSTRY_FULFILLED__ADMIN";
export const DELETE_INDUSTRY_REJECTED = "DELETE_INDUSTRY_REJECTED__ADMIN";

export const FETCH_CATEGORY_EACH = "FETCH_CATEGORY_EACH__ADMIN";
export const FETCH_CATEGORY_EACH_PENDING = "FETCH_CATEGORY_EACH_PENDING__ADMIN";
export const FETCH_CATEGORY_EACH_FULFILLED =
  "FETCH_CATEGORY_EACH_FULFILLED__ADMIN";
export const FETCH_CATEGORY_EACH_REJECTED =
  "FETCH_CATEGORY_EACH_REJECTED__ADMIN";

export const UNMOUNT_INDUSTRY = "UNMOUNT_INDUSTRY__ADMIN";
export const UNMOUNT_INDUSTRY_FULFILLED = "UNMOUNT_INDUSTRY_FULFILLED__ADMIN";
export const UNMOUNT_INDUSTRY_REJECTED = "UNMOUNT_INDUSTRY_REJECTED__ADMIN";

export const UNMOUNT_CATEGORY = "UNMOUNT_CATEGORY__ADMIN";
export const UNMOUNT_CATEGORY_FULFILLED = "UNMOUNT_CATEGORY_FULFILLED__ADMIN";
export const UNMOUNT_CATEGORY_REJECTED = "UNMOUNT_CATEGORY_REJECTED__ADMIN";

export const UNMOUNT_SUB_CATEGORY = "UNMOUNT_SUB_CATEGORY__ADMIN";
export const UNMOUNT_SUB_CATEGORY_FULFILLED =
  "UNMOUNT_SUB_CATEGORY_FULFILLED__ADMIN";
export const UNMOUNT_SUB_CATEGORY_REJECTED =
  "UNMOUNT_SUB_CATEGORY_REJECTED__ADMIN";

export const UNMOUNT_EXTRA_SECTION = "UNMOUNT_EXTRA_SECTION__ADMIN";
export const UNMOUNT_EXTRA_SECTION_FULFILLED__ADMIN =
  "UNMOUNT_EXTRA_SECTION_FULFILLED";
export const UNMOUNT_EXTRA_SECTION_REJECTED =
  "UNMOUNT_EXTRA_SECTION_REJECTED__ADMIN";

export const CREATE_INDUSTRY = "CREATE_INDUSTRY__ADMIN";
export const CREATE_INDUSTRY_PENDING = "CREATE_INDUSTRY_PENDING__ADMIN";
export const CREATE_INDUSTRY_FULFILLED = "CREATE_INDUSTRY_FULFILLED__ADMIN";
export const CREATE_INDUSTRY_REJECTED = "CREATE_INDUSTRY_REJECTED__ADMIN";

export const CREATE_GROUP = "CREATE_GROUP__ADMIN";
export const CREATE_GROUP_PENDING = "CREATE_GROUP_PENDING__ADMIN";
export const CREATE_GROUP_FULFILLED = "CREATE_GROUP_FULFILLED__ADMIN";
export const CREATE_GROUP_REJECTED = "CREATE_GROUP_REJECTED__ADMIN";

export const FETCH_GROUP = "FETCH_GROUP__ADMIN";
export const FETCH_GROUP_PENDING = "FETCH_GROUP_PENDING__ADMIN";
export const FETCH_GROUP_FULFILLED = "FETCH_GROUP_FULFILLED__ADMIN";
export const FETCH_GROUP_REJECTED = "FETCH_GROUP_REJECTED__ADMIN";

export const CREATE_USER = "CREATE_USER__ADMIN";
export const CREATE_USER_PENDING = "CREATE_USER_PENDING__ADMIN";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED__ADMIN";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED__ADMIN";

export const FETCH_USER = "FETCH_USER__ADMIN";
export const FETCH_USER_PENDING = "FETCH_USER_PENDING__ADMIN";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED__ADMIN";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED__ADMIN";

export const FETCH_EXTRA_SECTION = "FETCH_EXTRA_SECTION__ADMIN";
export const FETCH_EXTRA_SECTION_PENDING = "FETCH_EXTRA_SECTION_PENDING__ADMIN";
export const FETCH_EXTRA_SECTION_FULFILLED =
  "FETCH_EXTRA_SECTION_FULFILLED__ADMIN";
export const FETCH_EXTRA_SECTION_REJECTED =
  "FETCH_EXTRA_SECTION_REJECTED__ADMIN";

// AREA
export const CREATE_AREA_FULFILLED = "CREATE_AREA_FULFILLED__ADMIN";
export const CREATE_AREA_REJECTED = " CREATE_AREA_REJECTED__ADMIN";
export const CREATE_AREA_PENDING = "CREATE_AREA_PENDING__ADMIN";

export const FETCH_AREA_FULFILLED = "FETCH_AREA_FULFILLED__ADMIN";
export const FETCH_AREA_REJECTED = " FETCH_AREA_REJECTED__ADMIN";
export const FETCH_AREA_PENDING = "FETCH_AREA_PENDING__ADMIN";

// COUNTRY
export const CREATE_COUNTRY_FULFILLED = "CREATE_COUNTRY_FULFILLED__ADMIN";
export const CREATE_COUNTRY_REJECTED = " CREATE_COUNTRY_REJECTED__ADMIN";
export const CREATE_COUNTRY_PENDING = "CREATE_COUNTRY_PENDING__ADMIN";

export const FETCH_COUNTRY_FULFILLED = "FETCH_COUNTRY_FULFILLED__ADMIN";
export const FETCH_COUNTRY_REJECTED = " FETCH_COUNTRY_REJECTED__ADMIN";
export const FETCH_COUNTRY_PENDING = "FETCH_COUNTRY_PENDING__ADMIN";

export const DELETE_COUNTRY_PENDING = "DELETE_COUNTRY_PENDING__ADMIN";
export const DELETE_COUNTRY_FULFILLED = "DELETE_COUNTRY_FULFILLED__ADMIN";
export const DELETE_COUNTRY_REJECTED = "DELETE_COUNTRY_REJECTED__ADMIN";

// STATE
export const CREATE_STATE_FULFILLED = "CREATE_STATE_FULFILLED__ADMIN";
export const CREATE_STATE_REJECTED = " CREATE_STATE_REJECTED__ADMIN";
export const CREATE_STATE_PENDING = " CREATE_STATE_PENDING__ADMIN";

export const FETCH_STATE_FULFILLED = "FETCH_STATE_FULFILLED__ADMIN";
export const FETCH_STATE_REJECTED = " FETCH_STATE_REJECTED__ADMIN";
export const FETCH_STATE_PENDING = " FETCH_STATE_PENDING__ADMIN";

export const DELETE_STATE_PENDING = "DELETE_STATE_PENDING__ADMIN";
export const DELETE_STATE_FULFILLED = "DELETE_STATE_FULFILLED__ADMIN";
export const DELETE_STATE_REJECTED = "DELETE_STATE_REJECTED__ADMIN";

// DISTRICT
export const CREATE_DISTRICT_FULFILLED = "CREATE_DISTRICT_FULFILLED __ADMIN";
export const CREATE_DISTRICT_REJECTED = " CREATE_DISTRICT_REJECTED __ADMIN";
export const CREATE_DISTRICT_PENDING = " CREATE_DISTRICT_PENDING __ADMIN";

export const FETCH_DISTRICT_FULFILLED = "FETCH_DISTRICT_FULFILLED __ADMIN";
export const FETCH_DISTRICT_REJECTED = " FETCH_DISTRICT_REJECTED __ADMIN";
export const FETCH_DISTRICT_PENDING = " FETCH_DISTRICT_PENDING __ADMIN";

export const DELETE_DISTRICT_PENDING = "DELETE_DISTRICT_PENDING__ADMIN";
export const DELETE_DISTRICT_FULFILLED = "DELETE_DISTRICT_FULFILLED__ADMIN";
export const DELETE_DISTRICT_REJECTED = "DELETE_DISTRICT_REJECTED__ADMIN";

export const FETCH_COUNTRY_EACH_FULFILLED =
  "FETCH_COUNTRY_EACH_FULFILLED__ADMIN";
export const FETCH_COUNTRY_EACH_REJECTED =
  " FETCH_COUNTRY_EACH_REJECTED__ADMIN";
export const FETCH_COUNTRY_EACH_PENDING = "FETCH_COUNTRY_EACH_PENDING__ADMIN";

export const FETCH_STATE_EACH_FULFILLED = "FETCH_STATE_EACH_FULFILLED__ADMIN";
export const FETCH_STATE_EACH_REJECTED = " FETCH_STATE_EACH_REJECTED__ADMIN";
export const FETCH_STATE_EACH_PENDING = "FETCH_STATE_EACH_PENDING__ADMIN";

export const FETCH_DISTRICT_EACH_FULFILLED =
  "FETCH_DISTRICT_EACH_FULFILLED__ADMIN";
export const FETCH_DISTRICT_EACH_REJECTED =
  " FETCH_DISTRICT_EACH_REJECTED__ADMIN";
export const FETCH_DISTRICT_EACH_PENDING = "FETCH_DISTRICT_EACH_PENDING__ADMIN";

// CITY
export const CREATE_CITY_FULFILLED = "CREATE_CITY_FULFILLED__ADMIN";
export const CREATE_CITY_REJECTED = " CREATE_CITY_REJECTED__ADMIN";
export const CREATE_CITY_PENDING = " CREATE_CITY_PENDING__ADMIN";

export const FETCH_CITY_FULFILLED = "FETCH_CITY_FULFILLED__ADMIN";
export const FETCH_CITY_REJECTED = " FETCH_CITY_REJECTED__ADMIN";
export const FETCH_CITY_PENDING = " FETCH_CITY_PENDING__ADMIN";

export const FETCH_CITY_EACH_FULFILLED = "FETCH_CITY_EACH_FULFILLED__ADMIN";
export const FETCH_CITY_EACH_REJECTED = " FETCH_CITY_EACH_REJECTED__ADMIN";
export const FETCH_CITY_EACH_PENDING = "FETCH_CITY_EACH_PENDING__ADMIN";

export const CREATE_COMPANY_TYPE_FULFILLED =
  "CREATE_COMPANY_TYPE_FULFILLED__ADMIN";
export const CREATE_COMPANY_TYPE_REJECTED =
  " CREATE_COMPANY_TYPE_REJECTED__ADMIN";
export const CREATE_COMPANY_TYPE_PENDING =
  " CREATE_COMPANY_TYPE_PENDING__ADMIN";

export const CREATE_PAYMENT_METHODS_FULFILLED =
  "CREATE_PAYMENT_METHODS_FULFILLED__ADMIN";
export const CREATE_PAYMENT_METHODS_REJECTED =
  " CREATE_PAYMENT_METHODS_REJECTED__ADMIN";
export const CREATE_PAYMENT_METHODS_PENDING =
  " CREATE_PAYMENT_METHODS_PENDING__ADMIN";

export const FETCH_BUSINESS = "FETCH_BUSINESS__ADMIN";
export const FETCH_BUSINESS_PENDING = "FETCH_BUSINESS_PENDING__ADMIN";
export const FETCH_BUSINESS_FULFILLED = "FETCH_BUSINESS_FULFILLED__ADMIN";
export const FETCH_BUSINESS_REJECTED = "FETCH_BUSINESS_REJECTED__ADMIN";

export const EDIT_BUSINESS = "EDIT_BUSINESS__ADMIN";
export const EDIT_BUSINESS_PENDING = "EDIT_BUSINESS_PENDING__ADMIN";
export const EDIT_BUSINESS_FULFILLED = "EDIT_BUSINESS_FULFILLED__ADMIN";
export const EDIT_BUSINESS_REJECTED = "EDIT_BUSINESS_REJECTED__ADMIN";

export const DELETE_BUSINESS_PENDING = "DELETE_BUSINESS_PENDING__ADMIN";
export const DELETE_BUSINESS_FULFILLED = "DELETE_BUSINESS_FULFILLED__ADMIN";
export const DELETE_BUSINESS_REJECTED = "DELETE_BUSINESS_REJECTED__ADMIN";

export const BUSINESS_FILTER_ON_CHANGE = "BUSINESS_FILTER_ON_CHANGE__ADMIN";
export const CLEAR_BUSINESS_FILTER = "CLEAR_BUSINESS_FILTER__ADMIN";
export const CLEAR_BUSINESS_NAME_SEARCH = "CLEAR_BUSINESS_NAME_SEARCH__ADMIN";
export const BUSINESS_SET_SORT_BY = "BUSINESS_SET_SORT_BY__ADMIN";

export const CITY_FILTER_ON_CHANGE = "CITY_FILTER_ON_CHANGE__ADMIN";
export const CLEAR_CITY_FILTER = "CLEAR_CITY_FILTER__ADMIN";
export const CLEAR_CITY_NAME_SEARCH = "CLEAR_CITY_NAME_SEARCH__ADMIN";
export const CITY_SET_SORT_BY = "CITY_SET_SORT_BY__ADMIN";

export const FETCH_BUSINESS_EACH = "FETCH_BUSINESS_EACH__ADMIN";
export const FETCH_BUSINESS_EACH_PENDING = "FETCH_BUSINESS_EACH_PENDING__ADMIN";
export const FETCH_BUSINESS_EACH_FULFILLED =
  "FETCH_BUSINESS_EACH_FULFILLED__ADMIN";
export const FETCH_BUSINESS_EACH_REJECTED =
  "FETCH_BUSINESS_EACH_REJECTED__ADMIN";

export const CREATE_BUSINESS = "CREATE_BUSINESS__ADMIN";
export const CREATE_BUSINESS_PENDING = "CREATE_BUSINESS_PENDING__ADMIN";
export const CREATE_BUSINESS_FULFILLED = "CREATE_BUSINESS_FULFILLED__ADMIN";
export const CREATE_BUSINESS_REJECTED = "CREATE_BUSINESS_REJECTED__ADMIN";

export const FETCH_COMPANY_TYPE_FULFILLED =
  "FETCH_COMPANY_TYPE_FULFILLED__ADMIN";
export const FETCH_COMPANY_TYPE_REJECTED =
  " FETCH_COMPANY_TYPE_REJECTED__ADMIN";
export const FETCH_COMPANY_TYPE_PENDING = " FETCH_COMPANY_TYPE_PENDING__ADMIN";

export const FETCH_PAYMENT_METHODS_FULFILLED =
  "FETCH_PAYMENT_METHODS_FULFILLED__ADMIN";
export const FETCH_PAYMENT_METHODS_REJECTED =
  " FETCH_PAYMENT_METHODS_REJECTED__ADMIN";
export const FETCH_PAYMENT_METHODS_PENDING =
  " FETCH_PAYMENT_METHODS_PENDING__ADMIN";

export const FETCH_ADDRESS_TREE_FULFILLED =
  "FETCH_ADDRESS_TREE_FULFILLED__ADMIN";
export const FETCH_ADDRESS_TREE_REJECTED =
  " FETCH_ADDRESS_TREE_REJECTED__ADMIN";
export const FETCH_ADDRESS_TREE_PENDING = " FETCH_ADDRESS_TREE_PENDING__ADMIN";

export const REMOVE_CATEGORY_DATA_PENDING =
  "REMOVE_CATEGORY_DATA_PENDING__ADMIN";
export const REMOVE_CATEGORY_DATA_FULFILLED =
  "REMOVE_CATEGORY_DATA_FULFILLED__ADMIN";
export const REMOVE_CATEGORY_DATA_REJECTED =
  "REMOVE_CATEGORY_DATA_REJECTED__ADMIN";

export const FETCH_ADDRESS_TREE_GET_PENDING =
  "FETCH_ADDRESS_TREE_GET_PENDING__ADMIN";

export const FETCH_ADDRESS_TREE_LIST_PENDING =
  " FETCH_ADDRESS_TREE_LIST_PENDING__ADMIN";

export const UNMOUNT_DISTRICT = "UNMOUNT_DISTRICT__ADMIN";
export const UNMOUNT_CITY = "UNMOUNT_CITY__ADMIN";
export const UNMOUNT_AREA = "UNMOUNT_AREA__ADMIN";

export const UNMOUNT_INDUSTRY_DATA = "UNMOUNT_INDUSTRY_DATA__ADMIN";
export const UNMOUNT_CATEGORY_DATA = "UNMOUNT_CATEGORY_DATA__ADMIN";

export const TOGGLE_EDIT = "TOGGLE_EDIT__ADMIN";
