export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const CREATE_SUB_CATEGORY_PENDING = "CREATE_SUB_CATEGORY_PENDING";
export const CREATE_SUB_CATEGORY_FULFILLED = "CREATE_SUB_CATEGORY_FULFILLED";
export const CREATE_SUB_CATEGORY_REJECTED = "CREATE_SUB_CATEGORY_REJECTED";

export const FETCH_SUB_CATEGORY = "FETCH_SUB_CATEGORY";
export const FETCH_SUB_CATEGORY_PENDING = "FETCH_SUB_CATEGORY_PENDING";
export const FETCH_SUB_CATEGORY_FULFILLED = "FETCH_SUB_CATEGORY_FULFILLED";
export const FETCH_SUB_CATEGORY_REJECTED = "FETCH_SUB_CATEGORY_REJECTED";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_PENDING = "CREATE_CATEGORY_PENDING";
export const CREATE_CATEGORY_FULFILLED = "CREATE_CATEGORY_FULFILLED";
export const CREATE_CATEGORY_REJECTED = "CREATE_CATEGORY_REJECTED";

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_PENDING = "FETCH_CATEGORY_PENDING";
export const FETCH_CATEGORY_FULFILLED = "FETCH_CATEGORY_FULFILLED";
export const FETCH_CATEGORY_REJECTED = "FETCH_CATEGORY_REJECTED";

export const FETCH_INDUSTRY = "FETCH_INDUSTRY";
export const FETCH_INDUSTRY_PENDING = "FETCH_INDUSTRY_PENDING";
export const FETCH_INDUSTRY_FULFILLED = "FETCH_INDUSTRY_FULFILLED";
export const FETCH_INDUSTRY_REJECTED = "FETCH_INDUSTRY_REJECTED";

export const UNMOUNT_INDUSTRY = "UNMOUNT_INDUSTRY";
export const UNMOUNT_INDUSTRY_FULFILLED = "UNMOUNT_INDUSTRY_FULFILLED";
export const UNMOUNT_INDUSTRY_REJECTED = "UNMOUNT_INDUSTRY_REJECTED";

export const UNMOUNT_CATEGORY = "UNMOUNT_CATEGORY";
export const UNMOUNT_CATEGORY_FULFILLED = "UNMOUNT_CATEGORY_FULFILLED";
export const UNMOUNT_CATEGORY_REJECTED = "UNMOUNT_CATEGORY_REJECTED";

export const UNMOUNT_SUB_CATEGORY = "UNMOUNT_SUB_CATEGORY";
export const UNMOUNT_SUB_CATEGORY_FULFILLED = "UNMOUNT_SUB_CATEGORY_FULFILLED";
export const UNMOUNT_SUB_CATEGORY_REJECTED = "UNMOUNT_SUB_CATEGORY_REJECTED";

export const UNMOUNT_EXTRA_SECTION = "UNMOUNT_EXTRA_SECTION";
export const UNMOUNT_EXTRA_SECTION_FULFILLED =
  "UNMOUNT_EXTRA_SECTION_FULFILLED";
export const UNMOUNT_EXTRA_SECTION_REJECTED = "UNMOUNT_EXTRA_SECTION_REJECTED";

export const CREATE_INDUSTRY = "CREATE_INDUSTRY";
export const CREATE_INDUSTRY_PENDING = "CREATE_INDUSTRY_PENDING";
export const CREATE_INDUSTRY_FULFILLED = "CREATE_INDUSTRY_FULFILLED";
export const CREATE_INDUSTRY_REJECTED = "CREATE_INDUSTRY_REJECTED";

export const FETCH_EXTRA_SECTION = "FETCH_EXTRA_SECTION";
export const FETCH_EXTRA_SECTION_PENDING = "FETCH_EXTRA_SECTION_PENDING";
export const FETCH_EXTRA_SECTION_FULFILLED = "FETCH_EXTRA_SECTION_FULFILLED";
export const FETCH_EXTRA_SECTION_REJECTED = "FETCH_EXTRA_SECTION_REJECTED";

// AREA
export const CREATE_AREA_FULFILLED = "CREATE_AREA_FULFILLED";
export const CREATE_AREA_REJECTED = " CREATE_AREA_REJECTED";
export const CREATE_AREA_PENDING = "CREATE_AREA_PENDING";

export const FETCH_AREA_FULFILLED = "FETCH_AREA_FULFILLED";
export const FETCH_AREA_REJECTED = " FETCH_AREA_REJECTED";
export const FETCH_AREA_PENDING = "FETCH_AREA_PENDING";

// COUNTRY
export const CREATE_COUNTRY_FULFILLED = "CREATE_COUNTRY_FULFILLED";
export const CREATE_COUNTRY_REJECTED = " CREATE_COUNTRY_REJECTED";
export const CREATE_COUNTRY_PENDING = "CREATE_COUNTRY_PENDING";

export const FETCH_COUNTRY_FULFILLED = "FETCH_COUNTRY_FULFILLED";
export const FETCH_COUNTRY_REJECTED = " FETCH_COUNTRY_REJECTED";
export const FETCH_COUNTRY_PENDING = "FETCH_COUNTRY_PENDING";

// STATE
export const CREATE_STATE_FULFILLED = "CREATE_STATE_FULFILLED";
export const CREATE_STATE_REJECTED = " CREATE_STATE_REJECTED";
export const CREATE_STATE_PENDING = " CREATE_STATE_PENDING";

export const FETCH_STATE_FULFILLED = "FETCH_STATE_FULFILLED";
export const FETCH_STATE_REJECTED = " FETCH_STATE_REJECTED";
export const FETCH_STATE_PENDING = " FETCH_STATE_PENDING";

// DISTRICT
export const CREATE_DISTRICT_FULFILLED = "CREATE_DISTRICT_FULFILLED ";
export const CREATE_DISTRICT_REJECTED = " CREATE_DISTRICT_REJECTED ";
export const CREATE_DISTRICT_PENDING = " CREATE_DISTRICT_PENDING ";

export const FETCH_DISTRICT_FULFILLED = "FETCH_DISTRICT_FULFILLED ";
export const FETCH_DISTRICT_REJECTED = " FETCH_DISTRICT_REJECTED ";
export const FETCH_DISTRICT_PENDING = " FETCH_DISTRICT_PENDING ";

// CITY
export const CREATE_CITY_FULFILLED = "CREATE_CITY_FULFILLED";
export const CREATE_CITY_REJECTED = " CREATE_CITY_REJECTED";
export const CREATE_CITY_PENDING = " CREATE_CITY_PENDING";

export const FETCH_CITY_FULFILLED = "FETCH_CITY_FULFILLED";
export const FETCH_CITY_REJECTED = " FETCH_CITY_REJECTED";
export const FETCH_CITY_PENDING = " FETCH_CITY_PENDING";
