export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY__ADMIN";
export const CREATE_SUB_CATEGORY_PENDING = "CREATE_SUB_CATEGORY_PENDING__ADMIN";
export const CREATE_SUB_CATEGORY_FULFILLED =
  "CREATE_SUB_CATEGORY_FULFILLED__ADMIN";
export const CREATE_SUB_CATEGORY_REJECTED =
  "CREATE_SUB_CATEGORY_REJECTED__ADMIN";

export const FETCH_SUB_CATEGORY = "FETCH_SUB_CATEGORY__ADMIN";
export const FETCH_SUB_CATEGORY_PENDING = "FETCH_SUB_CATEGORY_PENDING__ADMIN";
export const FETCH_SUB_CATEGORY_FULFILLED =
  "FETCH_SUB_CATEGORY_FULFILLED__ADMIN";
export const FETCH_SUB_CATEGORY_REJECTED = "FETCH_SUB_CATEGORY_REJECTED__ADMIN";

export const CREATE_CATEGORY = "CREATE_CATEGORY__ADMIN";
export const CREATE_CATEGORY_PENDING = "CREATE_CATEGORY_PENDING__ADMIN";
export const CREATE_CATEGORY_FULFILLED = "CREATE_CATEGORY_FULFILLED__ADMIN";
export const CREATE_CATEGORY_REJECTED = "CREATE_CATEGORY_REJECTED__ADMIN";

export const FETCH_CATEGORY = "FETCH_CATEGORY__ADMIN";
export const FETCH_CATEGORY_PENDING = "FETCH_CATEGORY_PENDING__ADMIN";
export const FETCH_CATEGORY_FULFILLED = "FETCH_CATEGORY_FULFILLED__ADMIN";
export const FETCH_CATEGORY_REJECTED = "FETCH_CATEGORY_REJECTED__ADMIN";

export const FETCH_INDUSTRY = "FETCH_INDUSTRY__ADMIN";
export const FETCH_INDUSTRY_PENDING = "FETCH_INDUSTRY_PENDING__ADMIN";
export const FETCH_INDUSTRY_FULFILLED = "FETCH_INDUSTRY_FULFILLED__ADMIN";
export const FETCH_INDUSTRY_REJECTED = "FETCH_INDUSTRY_REJECTED__ADMIN";

export const UNMOUNT_INDUSTRY = "UNMOUNT_INDUSTRY__ADMIN";
export const UNMOUNT_INDUSTRY_FULFILLED = "UNMOUNT_INDUSTRY_FULFILLED__ADMIN";
export const UNMOUNT_INDUSTRY_REJECTED = "UNMOUNT_INDUSTRY_REJECTED__ADMIN";

export const UNMOUNT_CATEGORY = "UNMOUNT_CATEGORY__ADMIN";
export const UNMOUNT_CATEGORY_FULFILLED = "UNMOUNT_CATEGORY_FULFILLED__ADMIN";
export const UNMOUNT_CATEGORY_REJECTED = "UNMOUNT_CATEGORY_REJECTED__ADMIN";

export const UNMOUNT_SUB_CATEGORY = "UNMOUNT_SUB_CATEGORY__ADMIN";
export const UNMOUNT_SUB_CATEGORY_FULFILLED =
  "UNMOUNT_SUB_CATEGORY_FULFILLED__ADMIN";
export const UNMOUNT_SUB_CATEGORY_REJECTED =
  "UNMOUNT_SUB_CATEGORY_REJECTED__ADMIN";

export const UNMOUNT_EXTRA_SECTION = "UNMOUNT_EXTRA_SECTION__ADMIN";
export const UNMOUNT_EXTRA_SECTION_FULFILLED__ADMIN =
  "UNMOUNT_EXTRA_SECTION_FULFILLED";
export const UNMOUNT_EXTRA_SECTION_REJECTED =
  "UNMOUNT_EXTRA_SECTION_REJECTED__ADMIN";

export const CREATE_INDUSTRY = "CREATE_INDUSTRY__ADMIN";
export const CREATE_INDUSTRY_PENDING = "CREATE_INDUSTRY_PENDING__ADMIN";
export const CREATE_INDUSTRY_FULFILLED = "CREATE_INDUSTRY_FULFILLED__ADMIN";
export const CREATE_INDUSTRY_REJECTED = "CREATE_INDUSTRY_REJECTED__ADMIN";

export const FETCH_EXTRA_SECTION = "FETCH_EXTRA_SECTION__ADMIN";
export const FETCH_EXTRA_SECTION_PENDING = "FETCH_EXTRA_SECTION_PENDING__ADMIN";
export const FETCH_EXTRA_SECTION_FULFILLED =
  "FETCH_EXTRA_SECTION_FULFILLED__ADMIN";
export const FETCH_EXTRA_SECTION_REJECTED =
  "FETCH_EXTRA_SECTION_REJECTED__ADMIN";

// AREA
export const CREATE_AREA_FULFILLED = "CREATE_AREA_FULFILLED__ADMIN";
export const CREATE_AREA_REJECTED = " CREATE_AREA_REJECTED__ADMIN";
export const CREATE_AREA_PENDING = "CREATE_AREA_PENDING__ADMIN";

export const FETCH_AREA_FULFILLED = "FETCH_AREA_FULFILLED__ADMIN";
export const FETCH_AREA_REJECTED = " FETCH_AREA_REJECTED__ADMIN";
export const FETCH_AREA_PENDING = "FETCH_AREA_PENDING__ADMIN";

// COUNTRY
export const CREATE_COUNTRY_FULFILLED = "CREATE_COUNTRY_FULFILLED__ADMIN";
export const CREATE_COUNTRY_REJECTED = " CREATE_COUNTRY_REJECTED__ADMIN";
export const CREATE_COUNTRY_PENDING = "CREATE_COUNTRY_PENDING__ADMIN";

export const FETCH_COUNTRY_FULFILLED = "FETCH_COUNTRY_FULFILLED__ADMIN";
export const FETCH_COUNTRY_REJECTED = " FETCH_COUNTRY_REJECTED__ADMIN";
export const FETCH_COUNTRY_PENDING = "FETCH_COUNTRY_PENDING__ADMIN";

// STATE
export const CREATE_STATE_FULFILLED = "CREATE_STATE_FULFILLED__ADMIN";
export const CREATE_STATE_REJECTED = " CREATE_STATE_REJECTED__ADMIN";
export const CREATE_STATE_PENDING = " CREATE_STATE_PENDING__ADMIN";

export const FETCH_STATE_FULFILLED = "FETCH_STATE_FULFILLED__ADMIN";
export const FETCH_STATE_REJECTED = " FETCH_STATE_REJECTED__ADMIN";
export const FETCH_STATE_PENDING = " FETCH_STATE_PENDING__ADMIN";

// DISTRICT
export const CREATE_DISTRICT_FULFILLED = "CREATE_DISTRICT_FULFILLED __ADMIN";
export const CREATE_DISTRICT_REJECTED = " CREATE_DISTRICT_REJECTED __ADMIN";
export const CREATE_DISTRICT_PENDING = " CREATE_DISTRICT_PENDING __ADMIN";

export const FETCH_DISTRICT_FULFILLED = "FETCH_DISTRICT_FULFILLED __ADMIN";
export const FETCH_DISTRICT_REJECTED = " FETCH_DISTRICT_REJECTED __ADMIN";
export const FETCH_DISTRICT_PENDING = " FETCH_DISTRICT_PENDING __ADMIN";

// CITY
export const CREATE_CITY_FULFILLED = "CREATE_CITY_FULFILLED__ADMIN";
export const CREATE_CITY_REJECTED = " CREATE_CITY_REJECTED__ADMIN";
export const CREATE_CITY_PENDING = " CREATE_CITY_PENDING__ADMIN";

export const FETCH_CITY_FULFILLED = "FETCH_CITY_FULFILLED__ADMIN";
export const FETCH_CITY_REJECTED = " FETCH_CITY_REJECTED__ADMIN";
export const FETCH_CITY_PENDING = " FETCH_CITY_PENDING__ADMIN";
