export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL__WEBSITE";
export const TOGGLE_PHONE_VERIFICATION_MODAL =
  "TOGGLE_PHONE_VERIFICATION_MODAL__WEBSITE";
export const TOGGLE_REGISTER_MODAL = "TOGGLE_REGISTER_MODAL__WEBSITE";

export const SEARCH_QUERY = "SEARCH_QUERY__WEBSITE";
export const SEARCH_QUERY_PENDING = "SEARCH_QUERY_PENDING__WEBSITE";
export const SEARCH_QUERY_FULFILLED = "SEARCH_QUERY_FULFILLED__WEBSITE";
export const SEARCH_QUERY_REJECTED = "SEARCH_QUERY_REJECTED__WEBSITE";

export const SEARCH_RESULTS_PAGE = "SEARCH_RESULTS_PAGE__WEBSITE";
export const SEARCH_RESULTS_PAGE_PENDING =
  "SEARCH_RESULTS_PAGE_PENDING__WEBSITE";
export const SEARCH_RESULTS_PAGE_FULFILLED =
  "SEARCH_RESULTS_PAGE_FULFILLED__WEBSITE";
export const SEARCH_RESULTS_PAGE_REJECTED =
  "SEARCH_RESULTS_PAGE_REJECTED__WEBSITE";
