export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL__WEBSITE";

export const TOGGLE_REGISTER_MODAL = "TOGGLE_REGISTER_MODAL__WEBSITE";

export const SEARCH_QUERY = "SEARCH_QUERY__WEBSITE";
export const SEARCH_QUERY_PENDING = "SEARCH_QUERY_PENDING__WEBSITE";
export const SEARCH_QUERY_FULFILLED = "SEARCH_QUERY_FULFILLED__WEBSITE";
export const SEARCH_QUERY_REJECTED = "SEARCH_QUERY_REJECTED__WEBSITE";

export const STORE_USER_GEO_LOCATION = "STORE_USER_GEO_LOCATION__WEBSITE";
export const STORE_USER_GEO_LOCATION_FULFILLED =
  "STORE_USER_GEO_LOCATION_FULFILLED__WEBSITE";
export const STORE_USER_GEO_LOCATION_PENDING =
  "STORE_USER_GEO_LOCATION_PENDING__WEBSITE";
export const STORE_USER_GEO_LOCATION_REJECTED =
  "STORE_USER_GEO_LOCATION_REJECTED__WEBSITE";

export const SEARCH_RESULTS_PAGE = "SEARCH_RESULTS_PAGE__WEBSITE";
export const SEARCH_RESULTS_PAGE_PENDING =
  "SEARCH_RESULTS_PAGE_PENDING__WEBSITE";
export const SEARCH_RESULTS_PAGE_FULFILLED =
  "SEARCH_RESULTS_PAGE_FULFILLED__WEBSITE";
export const SEARCH_RESULTS_PAGE_REJECTED =
  "SEARCH_RESULTS_PAGE_REJECTED__WEBSITE";

export const FETCH_PROBLEM_TYPES = "FETCH_PROBLEM_TYPES__WEBSITE";
export const FETCH_PROBLEM_TYPES_PENDING =
  "FETCH_PROBLEM_TYPES_PENDING__WEBSITE";
export const FETCH_PROBLEM_TYPES_FULFILLED =
  "FETCH_PROBLEM_TYPES_FULFILLED__WEBSITE";
export const FETCH_PROBLEM_TYPES_REJECTED =
  "FETCH_PROBLEM_TYPES_REJECTED__WEBSITE";

export const CREATE_IMPROVE_LISTING = "CREATE_IMPROVE_LISTING__WEBSITE";
export const CREATE_IMPROVE_LISTING_PENDING =
  "CREATE_IMPROVE_LISTING_PENDING__WEBSITE";
export const CREATE_IMPROVE_LISTING_FULFILLED =
  "CREATE_IMPROVE_LISTING_FULFILLED__WEBSITE";
export const CREATE_IMPROVE_LISTING_REJECTED =
  "CREATE_IMPROVE_LISTING_REJECTED__WEBSITE";

export const TOGGLE_IMPROVE_LISTING_MODAL =
  "TOGGLE_IMPROVE_LISTING_MODAL__WEBSITE";
