export const TOGGLE_EDIT_MAIN = "TOGGLE_EDIT_MAIN__MINISITE";
export const TOGGLE_EDIT_ABOUT_US = "TOGGLE_EDIT_ABOUT_US__MINISITE";

export const FETCH_BUSINESS_PENDING = "FETCH_BUSINESS_PENDING__MINISITE";
export const FETCH_BUSINESS_FULFILLED = "FETCH_BUSINESS_FULFILLED__MINISITE";
export const FETCH_BUSINESS_REJECTED = "FETCH_BUSINESS_REJECTED__MINISITE";

export const UPDATE_BUSINESS_PENDING = "UPDATE_BUSINESS_PENDING__MINISITE";
export const UPDATE_BUSINESS_FULFILLED = "UPDATE_BUSINESS_FULFILLED__MINISITE";
export const UPDATE_BUSINESS_REJECTED = "UPDATE_BUSINESS_REJECTED__MINISITE";

export const FETCH_PART_BUSINESS = "FETCH_PART_BUSINESS__MINISITE";

export const CLEAR_MINISITE_DATA = "CLEAR_MINISITE_DATA__MINISITE";

export const UPDATE_ABOUT_PENDING = "UPDATE_ABOUT_PENDING__MINISITE";
export const UPDATE_ABOUT_FULFILLED = "UPDATE_ABOUT_FULFILLED__MINISITE";
export const UPDATE_ABOUT_REJECTED = "UPDATE_ABOUT_REJECTED__MINISITE";

export const UPDATE_LOGO_COVER_PHOTO_PENDING =
  "UPDATE_LOGO_COVER_PHOTO_PENDING__MINISITE";
export const UPDATE_LOGO_COVER_PHOTO_FULFILLED =
  "UPDATE_LOGO_COVER_PHOTO_FULFILLED__MINISITE";
export const UPDATE_LOGO_COVER_PHOTO_REJECTED =
  "UPDATE_LOGO_COVER_PHOTO_REJECTED__MINISITE";

export const UPLOAD_GALLERY_PHOTO_PENDING =
  "UPLOAD_GALLERY_PHOTO_PENDING__MINISITE";
export const UPLOAD_GALLERY_PHOTO_FULFILLED =
  "UPLOAD_GALLERY_PHOTO_FULFILLED__MINISITE";
export const UPLOAD_GALLERY_PHOTO_REJECTED =
  "UPLOAD_GALLERY_PHOTO_REJECTED__MINISITE";

export const DELETE_GALLERY_PHOTO_PENDING =
  "DELETE_GALLERY_PHOTO_PENDING__MINISITE";
export const DELETE_GALLERY_PHOTO_FULFILLED =
  "DELETE_GALLERY_PHOTO_FULFILLED__MINISITE";
export const DELETE_GALLERY_PHOTO_REJECTED =
  "DELETE_GALLERY_PHOTO_REJECTED__MINISITE";

export const CREATE_NEW_ALBUM_PENDING = "CREATE_NEW_ALBUM_PENDING__MINISITE";
export const CREATE_NEW_ALBUM_FULFILLED =
  "CREATE_NEW_ALBUM_FULFILLED__MINISITE";
export const CREATE_NEW_ALBUM_REJECTED = "CREATE_NEW_ALBUM_REJECTED__MINISITE";
