export const TOGGLE_EDIT_MAIN = "TOGGLE_EDIT_MAIN__MINISITE";
export const TOGGLE_EDIT_ABOUT_US = "TOGGLE_EDIT_ABOUT_US__MINISITE";

export const FETCH_BUSINESS_PENDING = "FETCH_BUSINESS_PENDING__MINISITE";
export const FETCH_BUSINESS_FULFILLED = "FETCH_BUSINESS_FULFILLED__MINISITE";
export const FETCH_BUSINESS_REJECTED = "FETCH_BUSINESS_REJECTED__MINISITE";

export const UPDATE_ABOUT_PENDING = "UPDATE_ABOUT_PENDING__MINISITE";
export const UPDATE_ABOUT_FULFILLED = "UPDATE_ABOUT_FULFILLED__MINISITE";
export const UPDATE_ABOUT_REJECTED = "UPDATE_ABOUT_REJECTED__MINISITE";

export const UPDATE_COVER_PHOTO_PENDING =
  "UPDATE_COVER_PHOTO_PENDING__MINISITE";
export const UPDATE_COVER_PHOTO_FULFILLED =
  "UPDATE_COVER_PHOTO_FULFILLED__MINISITE";
export const UPDATE_COVER_PHOTO_REJECTED =
  "UPDATE_COVER_PHOTO_REJECTED__MINISITE";
