export const TOGGLE_EDIT_MAIN = "TOGGLE_EDIT_MAIN__MINISITE";
export const TOGGLE_EDIT_ABOUT_US = "TOGGLE_EDIT_ABOUT_US__MINISITE";

export const FETCH_BUSINESS_PENDING = "FETCH_BUSINESS_PENDING__MINISITE";
export const FETCH_BUSINESS_FULFILLED = "FETCH_BUSINESS_FULFILLED__MINISITE";
export const FETCH_BUSINESS_REJECTED = "FETCH_BUSINESS_REJECTED__MINISITE";

export const SAVE_ABOUT_US = "SAVE_ABOUT_US__MINISITE";
